on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v2.3.4
      - name: Run tests
        run: |
          deno test
      - name: Generate npm package
        run: |
          deno run -A scripts/build-npm.ts 0.0.1
