on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: pasta_test
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v2.3.4
      - name: Run tests
        run: |
          deno test --allow-env --allow-net --unstable src/*.test.ts
      - name: Generate npm package
        run: |
          deno run -A scripts/build-npm.ts 0.0.1
